// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/layout/common/Button.vue')['default']
    Default: typeof import('./src/components/layout/Default.vue')['default']
    DefaultLayout: typeof import('./src/components/layout/DefaultLayout.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageWrapper: typeof import('./src/components/layout/common/ImageWrapper.vue')['default']
  }
}

export { }
