// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/button/index.vue')['default']
    Decoration: typeof import('./src/components/common/Decoration.vue')['default']
    DefaultLayout: typeof import('./src/components/layout/DefaultLayout.vue')['default']
    Event: typeof import('./src/components/layout/menu/event/index.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Logo: typeof import('./src/components/common/logo/index.vue')['default']
    MenuEvent: typeof import('./src/components/layout/menu/MenuEvent.vue')['default']
    MenuFooter: typeof import('./src/components/layout/menu/MenuFooter.vue')['default']
    MenuMobile: typeof import('./src/components/layout/menu/MenuMobile.vue')['default']
    MenuNormal: typeof import('./src/components/layout/menu/MenuNormal.vue')['default']
    Mobile: typeof import('./src/components/layout/menu/Mobile.vue')['default']
    Normal: typeof import('./src/components/layout/menu/normal/index.vue')['default']
    Spacer: typeof import('./src/components/common/Spacer.vue')['default']
  }
}

export { }
