export { default as IconArrow } from './arrow.svg?component'
export { default as InputHamburgher } from './hamburgher.svg?component'
export { default as InputHamburgher2 } from './hamburgher-2.svg?component'
export { default as InputClose } from './close.svg?component'
export { default as IconDecoration } from './decoration.svg?component'