export { default as IconArrow } from './arrow.svg?component'
export { default as InputHamburgher } from './hamburgher.svg?component'
export { default as InputHamburgherSymmetric } from './hamburgher-symmetric.svg?component'
export { default as InputClose } from './close.svg?component'
export { default as IconDecoration } from './decoration.svg?component'