// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./components/common/typography/Article.vue')['default']
    Button: typeof import('./components/common/button/Button.vue')['default']
    CustomButton: typeof import('./components/common/button/CustomButton.vue')['default']
    CustomImage: typeof import('./components/common/image/CustomImage.vue')['default']
    Decoration: typeof import('./components/common/Decoration.vue')['default']
    EventTitle: typeof import('./components/special/EventTitle.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Info: typeof import('./components/common/Info.vue')['default']
    Logo: typeof import('./components/common/logo/Logo.vue')['default']
    MenuEvent: typeof import('./components/menu/MenuEvent.vue')['default']
    MenuEvent_BACKUP_3742982: typeof import('./components/menu/MenuEvent_BACKUP_3742982.vue')['default']
    MenuEvent_BASE_3742982: typeof import('./components/menu/MenuEvent_BASE_3742982.vue')['default']
    MenuEvent_LOCAL_3742982: typeof import('./components/menu/MenuEvent_LOCAL_3742982.vue')['default']
    MenuEvent_REMOTE_3742982: typeof import('./components/menu/MenuEvent_REMOTE_3742982.vue')['default']
    MenuFooter: typeof import('./components/menu/MenuFooter.vue')['default']
    MenuFooter_BACKUP_3742982: typeof import('./components/menu/MenuFooter_BACKUP_3742982.vue')['default']
    MenuFooter_BASE_3742982: typeof import('./components/menu/MenuFooter_BASE_3742982.vue')['default']
    MenuFooter_LOCAL_3742982: typeof import('./components/menu/MenuFooter_LOCAL_3742982.vue')['default']
    MenuFooter_REMOTE_3742982: typeof import('./components/menu/MenuFooter_REMOTE_3742982.vue')['default']
    MenuMobile: typeof import('./components/menu/MenuMobile.vue')['default']
    MenuMobile_BACKUP_3742982: typeof import('./components/menu/MenuMobile_BACKUP_3742982.vue')['default']
    MenuMobile_BASE_3742982: typeof import('./components/menu/MenuMobile_BASE_3742982.vue')['default']
    MenuMobile_LOCAL_3742982: typeof import('./components/menu/MenuMobile_LOCAL_3742982.vue')['default']
    MenuMobile_REMOTE_3742982: typeof import('./components/menu/MenuMobile_REMOTE_3742982.vue')['default']
    MenuNormal: typeof import('./components/menu/MenuNormal.vue')['default']
    MenuNormal_BACKUP_3742982: typeof import('./components/menu/MenuNormal_BACKUP_3742982.vue')['default']
    MenuNormal_BASE_3742982: typeof import('./components/menu/MenuNormal_BASE_3742982.vue')['default']
    MenuNormal_LOCAL_3742982: typeof import('./components/menu/MenuNormal_LOCAL_3742982.vue')['default']
    MenuNormal_REMOTE_3742982: typeof import('./components/menu/MenuNormal_REMOTE_3742982.vue')['default']
    Paragraph: typeof import('./components/common/typography/Paragraph.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./components/common/Spacer.vue')['default']
    SplashScreen: typeof import('./components/layout/SplashScreen.vue')['default']
    Tooltip: typeof import('./components/common/Tooltip.vue')['default']
  }
}

export {}
