// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./components/common/typography/Article.vue')['default']
    Button: typeof import('./components/common/button/Button.vue')['default']
    Decoration: typeof import('./components/common/Decoration.vue')['default']
    EventTitle: typeof import('./components/special/EventTitle.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Image: typeof import('./components/common/image/Image.vue')['default']
    Info: typeof import('./components/common/Info.vue')['default']
    ListElement: typeof import('./components/common/list-element/ListElement.vue')['default']
    Logo: typeof import('./components/common/logo/Logo.vue')['default']
    MenuDetail: typeof import('./components/menu/menu-detail/MenuDetail.vue')['default']
    MenuFooter: typeof import('./components/menu/menu-footer/MenuFooter.vue')['default']
    MenuMobile: typeof import('./components/menu/menu-mobile/MenuMobile.vue')['default']
    MenuNormal: typeof import('./components/menu/menu-normal/MenuNormal.vue')['default']
    MenuNormalItem: typeof import('./components/menu/menu-normal/MenuNormalItem.vue')['default']
    Paragraph: typeof import('./components/common/typography/Paragraph.vue')['default']
    Parchment: typeof import('./components/special/Parchment.vue')['default']
    PopupMenu: typeof import('./components/common/popup-menu/PopupMenu.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollCard: typeof import('./components/special/ScrollCard.vue')['default']
    SelectField: typeof import('./components/common/select-field/SelectField.vue')['default']
    Spacer: typeof import('./components/common/Spacer.vue')['default']
    SplashScreen: typeof import('./components/layout/SplashScreen.vue')['default']
    Tooltip: typeof import('./components/common/tooltip/Tooltip.vue')['default']
  }
}

export {}
